# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/

name: Run Post Merge

on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  run-model-coverage:
    name: Model Coverage
    uses: ./.github/workflows/model_coverage.yml
    secrets: inherit
    with:
      trigger-sha: ${{ github.event.after }}

  run-generative-api-examples:
    name: Generative API Examples
    uses: ./.github/workflows/generative_api_examples.yml
    with:
      trigger-sha: ${{ github.event.after }}

  run-unittests-python:
    name: Unit Tests Python
    uses: ./.github/workflows/unittests_python.yml
    with:
      trigger-sha: ${{ github.event.after }}
